name: CI

on:
    push:
        branches: [main]

    pull_request:
        types: [opened, reopened, synchronize]

permissions: write-all, workflows

jobs:
    prettier:
          name: Prettier
          runs-on: ubuntu-latest

          steps:
              - uses: actions/checkout@v3
                with:
                    ref: ${{ github.head_ref }}

              - name: Run Commands
                run: |
                    npx prettier . --write --tab-width 4
                    git config --global user.name "free-domains-bot"
                    git config --global user.email "bot@freesubdomains.org"
                    git add .
                    set +e
                    git status | grep modified
                    if [ $? -eq 0 ]
                    then
                      set -e
                      git commit -m "Prettier"
                      git push
                    else
                      set -e
                      echo "No changes since last run"
                    fi
