name: Domains

on:
    workflow_dispatch: {}

    push:
        branches: [main]
        paths:
            - ".github/workflows/domains.yml"
            - "domains/*"
            - "scripts/ping.js"

    schedule:
        - cron: "0 0 * * *"

jobs:
    ping:
        name: Ping
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ secrets.BOT }}

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: 16

            - name: Create ping_results.txt
              run: |
                  touch ping_results.txt
                  echo "--- $(date +'%d/%m/%Y %T %Z') ---" >> ping_results.txt

            - name: Execute Script
              run: node scripts/ping.js

            - name: Commit
              run: |
                  git config --global user.email "bot@freesubdomains.org"
                  git config --global user.name "free-domains-bot"
                  git add ping_results.txt
                  git commit -m "Update Ping Results"
                  git push
