name: Raw API

on:
    push:
        branches: [main]
        paths:
            - "domains/*"
            - ".github/workflows/raw-api.yml"
            - "scripts/raw-api.js"

    workflow_dispatch:

jobs:
    update:
        name: Update
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: actions/checkout@v3
              with:
                  repository: free-domains/raw-api
                  path: raw-api
                  token: ${{ secrets.BOT }}

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: 16

            - name: Update Data
              run: node scripts/raw-api.js

            - name: Run Prettier
              run: npx prettier raw-api/index.json --write --tab-width 4 --print-width 1

            - name: Commit
              uses: cpina/github-action-push-to-another-repository@main
              with:
                  source-directory: "raw-api"
                  destination-github-username: free-domains
                  destination-repository-name: raw-api
                  user-email: bot@freesubdomains.org
                  user-name: free-domains-bot
                  commit-message: "Update Data via free-domains/register"
              env:
                  API_TOKEN_GITHUB: ${{ secrets.BOT }}
