name: Validation

on:
    workflow_dispatch: {}
    push:
        branches: [main]
        tags-ignore: ["**"]
        paths-ignore: ["**.md"]
    pull_request:
        paths-ignore: ["**.md"]

concurrency:
    group: ${{ github.ref }}-tests
    cancel-in-progress: true

jobs:
    records:
        name: Records
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: gacts/install-dnscontrol@v1
            - run: dnscontrol check

    schemas:
        name: Schemas
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: walbo/validate-json@v1.1.0
        with:
            schema-version: draft-07
            print-valid-files: true
            fail-on-missing-schema: true
            strict: false
            files: ./domains/**/*.json
